version: '3.4'
services:
  app:
    image: lucassimon98/springboot:1.0
    container_name: springboot_api
    links:
      - mysqldb:mysql
    ports:
      - "8080:8080"
    expose:
      - "8080"
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql
    container_name: springboot_db
    restart: always
    environment:
      MYSQL_DATABASE: spring_api
      MYSQL_USER: lucas
      MYSQL_PASSWORD: db123
      MYSQL_ROOT_PASSWORD: root

    ports:
      - "3306:3306"

    volumes:
      - javaapi_data:/var/lib/mysql
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger_ui_container
    ports:
      - "80:8080"
    volumes:
      - ./doc:/usr/share/nginx/html/doc
    environment:
      API_URL: doc/openapi.yaml



volumes:
  javaapi_data:
